ExAdmin/Models/ErrorViewModel.cs
namespace ExAdmin.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExAdmin/Controllers/DetailsController.cs
using ExDA;
using ExDA.Models;
using log4net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace ExAdmin.Controllers
{
	public class DetailsController : Controller
	{
		private readonly ILog _log = LogManager.GetLogger("Home");
		private readonly IConfiguration _cfg;
		private readonly IDA _da;
		public DetailsController(IConfiguration configuration, IDA da)
		{
			_cfg = configuration;
			_da = da;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult NewAddress(string clientCode)
		{
			Address adr = new Address() {  ClientCode = clientCode, IsNew = true };
			return View("Address", adr);
		}

		public IActionResult SaveAddress(Address address)
		{
			var adr = _da.GetClientAddresses(address.ClientCode);
			if(adr.Any(a => a.AddressType == address.AddressType))
			{
				ModelState.AddModelError("Line", "Address of this type already exists");
				return View("Address", address);
			}
			_da.SaveClientAddress(address);
			return View("Address", address);
		}
	}
}

ExAdmin/Controllers/HomeController.cs
using ExAdmin.Models;
using ExDA;
using ExDA.Models;
using log4net;
using log4net.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Configuration;
using System.Diagnostics;
using Microsoft.Extensions.Configuration;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Security.Cryptography;

#nullable disable

namespace ExAdmin.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILog _log = LogManager.GetLogger("Home");
        private readonly IConfiguration _cfg;
        private readonly IDA _da;

        public HomeController(IConfiguration configuration, IDA da)
        {
            _cfg = configuration;
            _da = da;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SearchClient(SearchClient search)
        {
            if (search == null || search.AllEmpty())
            {
                return View(search);
            }
            var clients = _da.FindClient(search);
            SearchResult res = new SearchResult();
            res.TotalITems = clients.Count;
            clients.ForEach(c => res.Results.Add(new SearchItem() 
            { 
                FirstName = c.FirstName, LastName = c.LastName, Code = c.Code,
                EntityType = c.EntityType,  CompanyName = c.CompanyName
            })); 
			return View("SearchResult", res);
        }

		public IActionResult EditClient(string clientCode)
		{
			Client cl = _da.GetClient(clientCode);
			cl.IsNew = false;
            cl.LoginName = cl.ClientLogin.FirstOrDefault()?.LoginName;
			return View("Client", cl);
		}

		public IActionResult NewClient()
        {
            Client cl = new Client();
            cl.EntityType = "P";
            cl.IsNew = true;
            return View("Client", cl);
        }

        [HttpPost]
        public IActionResult SaveClient(Client cl)
        {
            if (cl.IsNew)
            {
                cl.CreatedBy = User.Identity?.Name;
                cl.UpdatedBy = User.Identity?.Name;
                cl.DateUpdated = DateTime.Now;
                cl.DateCreated = DateTime.Now;
                cl.LoginName = cl.FirstName.Subs(0, 2) + cl.LastName.Subs(0, 10);
                cl.ClientLogin.Add(new ClientLogin() { LoginName = cl.LoginName, Password = cl.LoginName});
            }
            _da.SaveClient(cl);
            cl.IsNew = false;
            cl.LoginName = cl.ClientLogin.FirstOrDefault()?.LoginName;
			cl.Password = cl.ClientLogin.FirstOrDefault()?.Password;
			return View("Client", cl);
        }

		public IActionResult ResetPwd(string clientCode)
		{
			Client cl = _da.GetClient(clientCode);
			cl.IsNew = false;
            if(!cl.ClientLogin.Any())  // somehow no login was eve created
            {
				cl.LoginName = cl.FirstName.Subs(0, 2) + cl.LastName.Subs(0, 10);
                int addon = 1;
                while (_da.IsClientLoginNameExist(cl.LoginName))
                {
                    cl.LoginName += addon++;
                }
                cl.ClientLogin.Add(new ClientLogin() { LoginName = cl.LoginName, Password = cl.LoginName });
                _da.SaveClient(cl);
			}
			cl.LoginName = cl.ClientLogin.FirstOrDefault()?.LoginName;
            cl.Password = cl.LoginName;
            _da.ResetClientPassword(cl.LoginName, cl.LoginName);
			return View("Client", cl);
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExAdmin/Controllers/ListController.cs
using ExDA;
using ExDA.Models;
using log4net;
using Microsoft.AspNetCore.Mvc;

namespace ExAdmin.Controllers
{
	public class ListController : Controller
	{
		private readonly ILog _log = LogManager.GetLogger("List");
		private readonly IConfiguration _cfg;
		private readonly IDA _da;

		public ListController(IConfiguration configuration, IDA da)
		{
			_cfg = configuration;
			_da = da;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult PrevAdrPage(AddressPage model)
		{
			model.CurrPage = model.CurrPage <= 0 ? 0 : (model.CurrPage+1);
			return View("AddressList", model);
		}
		public IActionResult NextAdrPage(int pageNumber)
		{
			var res = _da.GetAddressPaged(20, pageNumber, "");
            res.CurrPage = pageNumber;
			return View("AddressList", res);
		}

		public IActionResult AddressList()
		{
			var res = _da.GetAddressPaged(20, 1, "");
			return View("AddressList", res);
		}

		public IActionResult Branch()
		{
			return View();
		}
	}
}

ExAdmin/Views/Details/Address.cshtml
@using ExDA.Models
@model Address;
<h1>Address</h1>
<form asp-action="SaveAddress">
	<div class="container">
		<input type="hidden" asp-for="IsNew" />
		<input type="hidden" asp-for="ClientCode" />
		<div class="row border rounded">
			<div class="col">
				<label asp-for="Line" class="control-label">Line</label>
				<input asp-for="Line" class="form-control" />
			</div>
			<div class="col">
				<label asp-for="AddressType" class="control-label">Line</label>
				<select asp-for="AddressType" class="form-control">
					<option value="MAIL">Mailing</option>
					<option value="RES">Residential</option>
				</select>
			</div>
			<div class="col">
				<label asp-for="Country" class="control-label">Country</label>
				<select asp-for="Country" class="form-control">
					<option value="CA">Canada</option>
					<option value="RU">Russia</option>
				</select>
			</div>
			<div class="col">
				<label asp-for="PostalCode" class="control-label">Postal code</label>
				<input asp-for="PostalCode" class="form-control" />
			</div>
		</div>
		<div class="row">
		<span asp-validation-for="Line" class="text-danger"></span>
		</div>
		<div class="row">
			<div class="col">
				<button class="btn btn-primary" type="submit">Submit Changes</button>
			</div>
		</div>
	</div>
</form>

ExAdmin/Views/Home/Client.cshtml
@using ExDA.Models
@model Client;

<h1>Client details</h1>
<form asp-action="SaveClient">
	<div class="container">
		<input type="hidden" asp-for="IsNew" />
		<input type="hidden" asp-for="Code" />
		<div class="row border rounded">
			<div class="form-group col">
				<label asp-for="EntityType" class="control-label">Client type</label>
				@{
					var dis = Model.IsNew ? null : "disabled";
				}
				<div @dis>
					<select asp-for="EntityType" class="form-control" id="et" disabled="@dis">
						<option value="P" selected>Person</option>
						<option value="B">Business</option>
					</select>
				</div>
			</div>
			<div class="form-group col" name="person1" id="person1">
				<label asp-for="FirstName" class="control-label">First name</label>
				<input asp-for="FirstName" class="form-control" />
			</div>
			<div class="form-group col" name="person2" id="person2">
				<label asp-for="LastName" class="control-label"></label>
				<input asp-for="LastName" class="form-control" />
			</div>
			<div class="form-group col" name="company" id="company">
				<label asp-for="CompanyName" class="control-label"></label>
				<input asp-for="CompanyName" class="form-control" />
			</div>
		</div>
		@if (!Model.IsNew)
		{
			<div class="row border rounded">
				<div class="form-group col">
					<label asp-for="LoginName" class="control-label"></label>
					<input asp-for="LoginName" class="form-control" disabled />
				</div>
				<div class="form-group col">
					<label asp-for="Password" class="control-label"></label>
					<input asp-for="Password" class="form-control" disabled />
				</div>
				<div class="form-group col">
					<a asp-action="ResetPwd" asp-route-clientCode="@Model.Code">Reset password</a>
				</div>
			</div>
		}
		<div class="row">
			<div class="col">Addresses</div>
		</div>
		<div class="row">
			<div class="col">
				<table>
					<tbody>

						@foreach (var ca in Model.ClientAddress)
						{
							<tr>
								<td>@ca.AddressType</td>
								<td>@ca.Address.Line</td>
							</tr>
						}
					</tbody>
				</table>
			</div>
		</div>
		<div class="row">
			<div class="col">Accounts</div>
		</div>
		<div class="row">
			<div class="col">
				<button class="btn btn-primary" type="submit">Submit Changes</button>
			</div>
			<div class="col">
				<a class="btn btn-info" type="button" asp-action="NewAddress" asp-controller="Details" asp-route-clientCode="@Model.Code">New Address</a>
			</div>
		</div>
	</div>
</form>

@section scripts{
	<script type="text/javascript">
		$(document).ready(function () {
			var initial = $('#et').val();
			toggle(initial);
			$('#et').change(function () {
				var value = $(this).val();
				//        alert('here: ' +value);
				toggle(value);
			});
		});
		function toggle(s) {
			if (s == 'P') {
				$('#person1').show();
				$('#person2').show();
				$('#company').hide();
			} else {
				$('#person1').hide();
				$('#person2').hide();
				$('#company').show();
			}
		}
	</script>
}

ExAdmin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ExAdmin/Views/Home/SearchClient.cshtml
@using ExDA.Models
@model SearchClient;

@{
	ViewData["Title"] = "Search Client";
}
<h1>@ViewData["Title"]</h1>

<form asp-action="SearchClient">
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="form-group col">
					<label asp-for="FirstName" class="control-label">First name</label>
					<input asp-for="FirstName" class="form-control" />
				</div>
				<div class="form-group col">
					<label asp-for="LastName" class="control-label">Last name</label>
					<input asp-for="LastName" class="form-control" />
				</div>
				<div class="form-group col">
					<label asp-for="CompanyName" class="control-label">Company</label>
					<input asp-for="CompanyName" class="form-control" />
				</div>
				<div class="form-group col">
					<label asp-for="Account" class="control-label">Account</label>
					<input asp-for="Account" class="form-control" />
				</div>
			</div>
			<div class="col"></div>
		</div>
		<div class="row">
			<div class="col">
				<button class="btn btn-primary" type="submit">Submit</button>
			</div>
		</div>
	</div>
</form>

ExAdmin/Views/Home/SearchResult.cshtml
@using ExDA.Models
@model SearchResult;

@{
	ViewData["Title"] = "Search Result";
}
<h1>@ViewData["Title"]</h1>

	<div class="container">
	@if(!Model.Results.Any())
	{
		<div class="row">Nothing found</div>
	}
	@foreach(SearchItem si in Model.Results)
		{
		<div class="row">
			@if(si.EntityType == "P"){
			<div class="col">
					<label asp-for="@si.FirstName" class="">First name</label>
					<input asp-for="@si.FirstName" class="" />
			</div>
			} else {
				<div class="col">
					<label asp-for="@si.CompanyName" class="">Company</label>
					<input asp-for="@si.CompanyName" class="" />
				</div>
			}
			<div class="col">
				<a asp-action="EditClient" asp-route-clientCode="@si.Code">Edit</a>
			</div>
		</div>
		}
	</div>

ExAdmin/Views/List/AddressList.cshtml
@using ExDA.Models
@model AddressPage;

<h1>Addresses</h1>
<div class="container">
	<input type="hidden" asp-for="CurrPage" />
	<div class="row border rounded">
		<div class="col">Filter:</div>
		<div class="col">
			<input type="text" />
		</div>
		<div class="col">
			<button type="submit">Apply</button>
		</div>
	</div>
	<div class="row border rounded">
		<div class="col">
			<table>
				<thead>
					<tr>
						<th>Country</th>
						<th>Address</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Model.Items)
					{
						<tr>
							<td>@item.Country</td>
							<td>@item.Line</td>
						</tr>
					}
				</tbody>
			</table>
			<a asp-action="PrevAdrPage" asp-route-pageNumber="@(Model.CurrPage - 1)" class="btn btn-default">Previous</a>
			<a asp-action="NextAdrPage" asp-route-pageNumber="@(Model.CurrPage + 1)" class="btn btn-default">Next</a>
		</div>
	</div>
</div>

ExAdmin/Views/List/Branch.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

ExAdmin/Views/List/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

ExAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - ExAdmin</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/ExAdmin.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="SearchClient">Search</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="NewClient">New Client</a>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link text-dark dropdown-toggle" href="#" id="listDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Lists</a>
							<div class="dropdown-menu" aria-labelledby="listDropdown">
								<a class="dropdown-item text-dark" asp-area="" asp-controller="List" asp-action="AddressList">Address</a>
								<a class="dropdown-item text-dark" asp-area="" asp-controller="List" asp-action="Branch">Branch</a>
							</div>
						</li>
					</ul>
					<p class="nav navbar-text">Hello, @User.Identity?.Name!</p>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2023 - ExAdmin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>